---

enabled: true
restylers:
# Use the latest prettier restyler (with prettier 2.0)
  - prettier:
      image: restyled/restyler-prettier:v2.0.2-1
      include:
        - '**/*.js'
        - '**/*.ts'
        - '**/*.html'
        - '**/*.md'
        - '**/*.yml'
        - '**/*.yaml'
        - '**/*.json'
        - '**/*.css'
        - '**/*.scss'
