name: CI
on:
  pull_request:
    branches: [ master ]
    paths:
    - 'react-with-json-logic/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Packages
      run: npm install
      working-directory: react-with-json-logic/
    - name: Build covquestions package
      run: npm install
      run: npm run build
      working-directory: covquestions-js/
    - name: Link covquestions package
      run: npm link ../covquestions-js
      working-directory: react-with-json-logic/
    - name: Check format
      run: npm run lint
      working-directory: react-with-json-logic/
    - name: Run tests
      run: CI=true npm run test
      working-directory: react-with-json-logic/
    - name: Build App
      run: npm run build
      working-directory: react-with-json-logic/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: react-app
        # Directory containing files to upload
        path: react-with-json-logic/build/
      
